#!/bin/bash

echo "🔍 Checking Cobytes Security Platform Deployment Status"
echo "======================================================"
echo ""
echo "📱 App Dashboard: https://cloud.digitalocean.com/apps/93a8fcec-94b3-4c24-9c7f-3b23c6b37b5c"
echo ""
echo "📝 REQUIRED MANUAL STEPS:"
echo ""
echo "1. Go to Settings → api → Environment Variables"
echo "2. Add these variables:"
echo "   - DATABASE_URL (with your password)"
echo "   - JWT_SECRET"
echo "   - JWT_REFRESH_SECRET"
echo "   - PENTEST_TOOLS_API_KEY"
echo "   - And others listed in DEPLOYMENT_INSTRUCTIONS.md"
echo ""
echo "3. Click 'Save' and then 'Deploy'"
echo ""
echo "🚀 GitHub Actions should automatically deploy on push"
echo "   Check: https://github.com/RoscoNL/cobytes-security-platform/actions"
echo ""
echo "📊 Database is ready at:"
echo "   private-db-securityscan-ams3-do-user-170668-0.k.db.ondigitalocean.com:25060"
echo ""
echo "🌐 Once deployed, your app will be at:"
echo "   https://securityscan.cobytes.com"
echo ""
echo "✅ SSL certificate is embedded in Docker image"
echo "✅ TypeScript path aliases are fixed"
echo "✅ Automatic deployments are configured"
echo ""
echo "⏳ Waiting for environment variables to be configured manually..."