services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cobytes-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cobytes_db
      POSTGRES_USER: cobytes_user
      POSTGRES_PASSWORD: cobytes_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cobytes_user -d cobytes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cobytes-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
      DATABASE_URL: postgresql://cobytes_user:cobytes_password@postgres:5432/cobytes_db
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-change-in-production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-refresh-secret-change-in-production}
      PENTEST_TOOLS_API_KEY: ${PENTEST_TOOLS_API_KEY:-43cIriuvQ9qEeFFaYbFDKpfzwLWuUA92tq7sOpzJ046a87e7}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3001}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs

  # Frontend (if exists)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cobytes-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      REACT_APP_API_URL: http://localhost:3000/api/v1
    depends_on:
      - backend
    profiles:
      - with-frontend

  # pgAdmin (optional, for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cobytes-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cobytes.nl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:

networks:
  default:
    name: cobytes-network