name: cobytes-security-platform-prod
region: ams
domains:
  - domain: api.securityscan.cobytes.com
    type: PRIMARY

databases:
  - name: cobytes-db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb
    num_nodes: 1

services:
  - name: api
    git:
      repo_clone_url: https://github.com/RoscoNL/cobytes-security-platform.git
      branch: main
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PORT
        value: "3001"
        scope: RUN_TIME
      - key: DATABASE_URL
        value: ${cobytes-db.DATABASE_URL}
        scope: RUN_TIME
      - key: JWT_SECRET
        type: SECRET
        scope: RUN_TIME
      - key: JWT_REFRESH_SECRET
        type: SECRET
        scope: RUN_TIME
      - key: PENTEST_TOOLS_API_KEY
        value: "43cIriuvQ9qEeFFaYbFDKpfzwLWuUA92tq7sOpzJ046a87e7"
        scope: RUN_TIME
      - key: PENTEST_TOOLS_API_URL
        value: "https://app.pentest-tools.com/api/v2"
        scope: RUN_TIME
      - key: CORS_ORIGIN
        value: "https://securityscan.cobytes.com,http://localhost:3000"
        scope: RUN_TIME
      - key: REDIS_URL
        value: "redis://localhost:6379"
        scope: RUN_TIME
      - key: MULTISAFEPAY_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: MULTISAFEPAY_SITE_ID
        type: SECRET
        scope: RUN_TIME
      - key: MULTISAFEPAY_SITE_CODE
        type: SECRET
        scope: RUN_TIME
      - key: HOSTFACT_API_KEY
        value: "6685741463b3d6791e31779df6a99a92"
        scope: RUN_TIME
      - key: HOSTFACT_URL
        value: "https://secure.cobytes.com/Pro/apiv2/api.php"
        scope: RUN_TIME
      - key: SESSION_SECRET
        type: SECRET
        scope: RUN_TIME
    
static_sites:
  - name: frontend
    git:
      repo_clone_url: https://github.com/RoscoNL/cobytes-security-platform.git
      branch: main
    source_dir: /frontend
    build_command: npm install && npm run build
    output_dir: build
    index_document: index.html
    catchall_document: index.html
    envs:
      - key: REACT_APP_API_URL
        value: "https://api.securityscan.cobytes.com/api"
        scope: BUILD_TIME
      - key: REACT_APP_WS_URL
        value: "wss://api.securityscan.cobytes.com"
        scope: BUILD_TIME
      - key: NODE_ENV
        value: production
        scope: BUILD_TIME

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: api
    - match:
        path:
          prefix: /
      component:
        name: frontend

jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    git:
      repo_clone_url: https://github.com/RoscoNL/cobytes-security-platform.git
      branch: main
    source_dir: /backend
    run_command: npm run migrate
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DATABASE_URL
        value: ${cobytes-db.DATABASE_URL}
        scope: RUN_TIME